### ISSUE TITLE
Change package name to humbug

### ISSUE THREAD

**Issue by theofidry** [padraic/file_get_contents#16]
Although I'm not really sure if it's worth to deprecate a package just for the change name...

**Comment by padraic** [comment]
Weirdly, I checked this last night out of curiousity. You can change a package name, but only by abandoning the old one on Packagist, i.e. it's marked abandoned and there's no guarantee downstream users would switch names in any timely fashion. Probably not worth it. I understand Packagist can't do aliasing/redirects because they have some security around package name spoofing.

**Comment by padraic** [comment]
`bamarni/composer-bin-plugin` - is there an post-install command using it to be added?

**Comment by Nyholm** [comment]
Potato potato... there is no clear win in doing this.  I vote for not renaming.
